FROM maven:3.9.7-eclipse-temurin-17 AS builder

WORKDIR /build

COPY pom.xml .
RUN mvn dependency:go-offline -q

COPY src ./src
RUN mvn clean package -DskipTests -q

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

RUN addgroup -S notifyflow && adduser -S notifyflow -G notifyflow
USER notifyflow

COPY --from=builder /build/target/notifyflow-1.0.0.jar app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", \
            "-Djava.security.egd=file:/dev/./urandom", \
            "-XX:+UseContainerSupport", \
            "-XX:MaxRAMPercentage=75.0", \
            "-Dspring.profiles.active=render", \
            "app.jar"]
