package com.notifyflow.util;

import com.notifyflow.model.enums.NotificationChannel;
import org.springframework.stereotype.Component;
import org.springframework.util.DigestUtils;

import java.nio.charset.StandardCharsets;

/**
 * Centralises Redis key construction for all NotifyFlow use cases.
 *
 * Having keys defined in one place means:
 * - No magic strings scattered across services
 * - Key format changes require editing one file
 * - Easy to audit all cached data in Redis with a prefix scan
 *
 * Key patterns:
 *   Deduplication:         dedup:{userId}:{channel}:{md5(message)}
 *   User preferences:      user-preferences::{userId}
 *   Notification history:  notification-history::{userId}:{page}:{size}
 *
 * Note: Spring Cache (@Cacheable) auto-generates keys for
 * user-preferences and notification-history caches.
 * This util is used for MANUAL Redis operations (deduplication).
 */
@Component
public class RedisKeyUtil {

    // ── Key Prefixes ───────────────────────────────────────────────

    private static final String DEDUP_PREFIX    = "dedup";
    private static final String SEPARATOR       = ":";

    // ── Deduplication Keys ─────────────────────────────────────────

    /**
     * Builds the deduplication key for a notification.
     *
     * Format: dedup:{userId}:{channel}:{md5(message)}
     *
     * MD5 is used here purely as a compact fingerprint —
     * NOT for cryptographic security. Message content can be
     * arbitrarily long; MD5 keeps the key at a fixed 32-char hex string.
     *
     * Example: dedup:42:EMAIL:d41d8cd98f00b204e9800998ecf8427e
     *
     * @param userId  the target user's ID
     * @param channel the notification delivery channel
     * @param message the notification message body
     * @return a deterministic Redis key for this notification
     */
    public String buildDedupKey(Long userId,
                                NotificationChannel channel,
                                String message) {
        String messageHash = md5Hex(message);
        return DEDUP_PREFIX
                + SEPARATOR + userId
                + SEPARATOR + channel.name()
                + SEPARATOR + messageHash;
    }

    /**
     * Builds the deduplication key using title + message combined.
     * Use this variant when title changes should also invalidate dedup.
     *
     * Format: dedup:{userId}:{channel}:{md5(title|message)}
     *
     * @param userId  the target user's ID
     * @param channel the notification delivery channel
     * @param title   the notification title
     * @param message the notification message body
     * @return a deterministic Redis key combining title and message
     */
    public String buildDedupKeyWithTitle(Long userId,
                                         NotificationChannel channel,
                                         String title,
                                         String message) {
        String combined = title + "|" + message;
        String combinedHash = md5Hex(combined);
        return DEDUP_PREFIX
                + SEPARATOR + userId
                + SEPARATOR + channel.name()
                + SEPARATOR + combinedHash;
    }

    // ── Cache Key Helpers (for @CacheEvict targets) ────────────────

    /**
     * Returns the Spring Cache key for a user's notification history page.
     * Must match the key generated by @Cacheable in PreferenceService.
     *
     * Spring Cache key format: {cacheName}::{spEL result}
     * For @Cacheable(key = "#userId + ':' + #page + ':' + #size")
     * the full Redis key becomes:
     *   notification-history::{userId}:{page}:{size}
     *
     * @param userId the user whose history is cached
     * @param page   the page number
     * @param size   the page size
     * @return the Spring Cache key string (without cache name prefix)
     */
    public String buildHistoryCacheKey(Long userId, int page, int size) {
        return userId + SEPARATOR + page + SEPARATOR + size;
    }

    /**
     * Returns the Spring Cache key for a user's preferences.
     * Matches the key generated by @Cacheable(key = "#userId").
     *
     * Full Redis key: notification-history::{userId}
     *
     * @param userId the user whose preferences are cached
     * @return the Spring Cache key string
     */
    public String buildPreferencesCacheKey(Long userId) {
        return String.valueOf(userId);
    }

    // ── Internal helpers ───────────────────────────────────────────

    /**
     * Computes MD5 hex digest of a string.
     * Spring's DigestUtils used to avoid pulling in Apache Commons.
     *
     * @param input the string to hash
     * @return 32-character lowercase hex MD5 digest
     */
    private String md5Hex(String input) {
        return DigestUtils.md5DigestAsHex(
                input.getBytes(StandardCharsets.UTF_8));
    }
}